### ISSUE TITLE
Wrong array validation

### ISSUE THREAD

**Issue by olegrok** [tarantool/avro-schema#117]
```
schema = { type = 'array', items = 'string' }
ok, sch = avro.create(schema)
data = { value = '123', lol = 'kek' }
tarantool> avro.validate(sch, data)
---
- true
- []
...
```

Expected something as `Expecting ARRAY, encountered MAP`

avro-schema v.3.0.2
Tarantool v2.0.5 and v.1.10.2

**Comment by Totktonada** [comment]
Need to check `i` type here: https://github.com/tarantool/avro-schema/blob/126b8864805b4d80974cda33b351af02c7cd88b2/avro_schema/frontend.lua#L882
