### ISSUE TITLE
Non-informative error on empty model creation

### ISSUE THREAD

**Issue by olegrok** [tarantool/avro-schema#129]
```lua
tarantool> require('avro_schema').create({})
---
- false
- Union type must have at least one branch
...
```

Firstly, I don't think that we should prohibit to create empty model.
Secondly, if we ban empty models we should returns more informative error message.

**Comment by olegrok** [comment]
Also seem that there is a test for such behaviour: https://github.com/tarantool/avro-schema/blob/19e05824066297a457d7ffe1b89a0d73f232430c/test/ddt_suite/invalid.lua#L208-L211

**Comment by Totktonada** [comment]
It is a union and it is empty. I'm not sure we can provide a better message.

**Comment by olegrok** [comment]
Agree. Could be resolved at the application level.
