### ISSUE TITLE
validation for "long" allows "string"

### ISSUE THREAD

**Issue by olegrok** [tarantool/avro-schema#133]
```
tarantool> avro_schema.validate(select(2, avro_schema.create('long')), '42')
---
- true
- '42'
...

tarantool> avro_schema.validate(select(2, avro_schema.create('long')), 42)
---
- true
- 42
...
```

Broken here - https://github.com/tarantool/avro-schema/commit/23be8480e153521772adf6317f04c7d03c65a67c

**Comment by Totktonada** [comment]
`validate()` behaviour should be consistent with `flatten()`. It is not so in the case:

```yml
tarantool> avro_schema = require('avro_schema')
tarantool> ok, h = avro_schema.create({type = 'record', name = 'r', fields = {{type = 'long', name = 'f'}}})
tarantool> ok, m = avro_schema.compile(h)
tarantool> m.flatten({f = '42'})
---
- false
- 'f: Expecting LONG, encountered STR'
...
tarantool> m.flatten({f = 42})
---
- true
- [42]
...
```

I would consider `flatten` behaviour as the right one.

**Comment by olegrok** [comment]
Need for https://github.com/tarantool/tdg/issues/749
There is a patch - https://github.com/tarantool/avro-schema/pull/134, no review.

**Comment by Totktonada** [comment]
Thanks for the reminder, I'll give a glance soon.
