### ISSUE TITLE
RPM fails to build with packpack

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/avro-schema#148]
See build log below.

[build.log](https://github.com/tarantool/avro-schema/files/11015468/build.log)

**Comment by LeonidVas** [comment]
Seems like https://github.com/tarantool/queue/commit/769bc725f8fe60714996a6bde5cf6c260d9b92fd

**Comment by DifferentialOrange** [comment]
> Seems like [tarantool/queue@769bc72](https://github.com/tarantool/queue/commit/769bc725f8fe60714996a6bde5cf6c260d9b92fd)

It seems that it is really the issue. packpack works fine for EL 7 and 8, Fedora 30, 31 and 32, but starts to fail on Fedora 33 and newer. Applying this patch is not enough. I seems that CMakeLists must respect out-of source rpm build.
