### ISSUE TITLE
Avro serialization and deserialization 

### ISSUE THREAD

**Issue by weiqj** [tarantool/avro-schema#25]
Hi, thanks for your effort. I am looking for a Lua library to do Avro binary serialization and deserialization. After going through your library I noticed that it only deals with MsgPack array. The decoder doesn't even use the schema. It appears the current architecture is not capable of processing the Avro binary records, especially on the decoding side. 
Correct me if I am wrong.

**Comment by bigbes** [comment]
You're right. This library supports only MsgPack and was created for using in Tarantool storage layer (heavily depends on Tarantool internal libraries)

**Comment by Khatskevich** [comment]
The ticket deso not assume any action
