### ISSUE TITLE
Implement a universal JSON verificator

### ISSUE THREAD

**Issue by Totktonada** [tarantool/avro-schema#26]
The following features desired to be parts of a universal JSON verificator and does not supported by avro-schema:

1. ~~Nullability of an object field~~ (resolved).
2. Unions w/o an explicit type specification:
   2.1. A union as a field type.
   2.2. A union as part of fields list, kinda this: `{f1, f2, {{f3a, f4a}, {f3b, f4b}}, f5}`.
3. ~~removed~~
4. Support for custom types, type inheritance and type validators:
   4.1. Each custom type must (?) have a parent, which is a basic type (like int, string) or an other custom type.
   4.2. Each custom type must (?) have validator in form of a PCRE regexp or a function returns `ok, err`.
   4.3. Validate length of an array by min / max bounds.
5. Support for constant field values.
6. A string contains hyphen as a name of an object field.
7. Handle the `null` field value and absence of the value as different cases.
8. Construct a schema by parts: match the same sub-schemas instead of giving an error re names clash.

The first one point (nullability) is most annoing lack of a feature.

The features will extend avro-schema standard.

**Comment by Totktonada** [comment]
Related to the 1st point: https://github.com/tarantool/avro-schema/issues/20

**Comment by racktear** [comment]
Please implement it as part of a separate module, and not in avro-schema

**Comment by Khatskevich** [comment]
String length, number boundaries... verification, auto fields can be helpful.
Should it be implemented as an extension to the Avro schema&

**Comment by akudiyar** [comment]
I'd like to add an option for possible regex (or at least Lua-pattern) validation:
```
{ name = 'name', type = 'string', format = '[a-zA-Z_]\w*' }
```

**Comment by Totktonada** [comment]
Reverted Alexey's Kh. changes.

Alexey, please, never do such actions silently. I disagree with some changes you made. When you have thoughts, please, add them as a comment or a separate issue. Or when you are 100% sure that the original author will agree with you, then at least leave a message about your edits.

**Comment by Totktonada** [comment]
We can glance on https://github.com/api7/jsonschema.

Anyway, the issue is a bunch of thoughts and I don't want to track it in this form. Closing so.
