### ISSUE TITLE
can not use complex type in record fields

### ISSUE THREAD

**Issue by grayflow** [tarantool/avro-schema#27]
tarantool> schema
---
- type: record
  name: test
  fields:
  - type: string
    name: data
  - type: enum
    name: status
    symbols:
    - A
    - B
...

tarantool> avro.create(schema)
---
- false
- 'test/status: Unknown Avro type: enum'
...

tarantool>

but here create call is expected to success

**Comment by Totktonada** [comment]
Use fields::type = {type = 'enum', name = 'status', symbols = {'A', 'B'}}. It is according to the Avro standard.

**Comment by grayflow** [comment]
oh, i see, so verbose!
thanks
