### ISSUE TITLE
Implement schema fingerprinting and parsing canonical form

### ISSUE THREAD

**Issue by racktear** [tarantool/avro-schema#30]
Please refer to the spec: https://avro.apache.org/docs/1.8.1/spec.html#Schema+Fingerprints

Fingerprinting is necessary to tag objects with a schema ID to figure out which schema was used to produce them

**Comment by Khatskevich** [comment]
I suppose, that we can ignore some rules mentioned in Avro specification.
I think, that such fingerprinting algorithm would be enough for all needs:
1. Prepare normalized AST as Lua's simple data structure
  - consists of arrays, maps, and primitive types only
  - names converted to full named
  - remove all attributes except: _type, name, fields, symbols, items, values, size_
2. create a function which work on such data structures
  - panic if faces something except maps, arrays or primitive types
  - sort map keys before hashing
  - return outbut as a variable length blob (8bytes as a default)
  - use some non-trivial hashing function under the hood (sha256)

**Comment by Totktonada** [comment]
Proposed to use only 'native' avro-schema fields by default (those that listed for a fingerprint by the spec), but provide an argument to expand the list of fields. The list cannot expand wider than the list of fields preserved in ast.
