### ISSUE TITLE
Can't reload code of avro-schema

### ISSUE THREAD

**Issue by knazarov** [tarantool/avro-schema#34]
When I set `package.loaded['avro-schema'] = nil` and attempt to `require()` it again, I get:

```lua
tarantool> ---
- error: '...antool/ib-core/.rocks/share/tarantool/avro_schema/il.lua:12: attempt
    to redefine ''schema_il_Opcode'''
...
```

UPD: ability to do hot code reload is very important for my development workflow

**Comment by theonedemon** [comment]
up
