### ISSUE TITLE
Cyclic type declaration

### ISSUE THREAD

**Issue by racktear** [tarantool/avro-schema#40]
Sometimes I need types that contain each other in their fields. Example:

```lua
{
        {
            name="typeA",
            type="record",
            fields={{name='fieldA', type='typeB'}}
        },
        {
            name="typeB",
            type="record",
            fields={{name='fieldB', type='typeA'}},
        }
}
```

Currently the library can't parse such schema, complaining that typeB is not defined.

**Comment by kyukhin** [comment]
Looks like Avro spec v1.8.2 explicitly prohibits such cycles.
Quote from here [1]:
> A schema or protocol may not contain multiple definitions of a fullname. Further, a name must be defined before it is used ("before" in the depth-first, left-to-right traversal of the JSON parse tree, where the types attribute of a protocol is always deemed to come "before" the messages attribute.)

[1] -  http://avro.apache.org/docs/1.8.2/spec.html

**Comment by Khatskevich** [comment]
The feature described in the comment abode considered not relevant.
