### ISSUE TITLE
nullable type reference exported as type definition

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/avro-schema#49]
snippet
```
local json = require('json')
local schema = {
    name = "X",
    type = "record",
    fields = {
        {
            name = "first",
            type = {
                name = "first",
                type = "fixed",
                size = 16
            }

        },
        {
            name = "second",
            type = "first*"
        }
    }
}
print(json.encode(schema))
ok, res = avro.create(schema, {deferred_definition=true})
schema = avro.export(res)
print(json.encode(schema))
ok, res = avro.create(schema, {deferred_definition=true})
print(ok, res)
```
result
```
false	X/second/<fixed>: Type name already defined: first
```

Reason:
Export function uses type tables as keys to determine if it is already exported, however if type definition and type reference have diferent nullabilities, `deepcopy` function is called and tables have different addresses.

**Comment by Totktonada** [comment]
In the example you provide you defined type 'first' once (but it assumes definition of type 'first*' too), the define 'first*' (which assumes definition of the type 'first'). The example should fail. To use 'first*' you must reference it, but not define twice.
