### ISSUE TITLE
reimplement flatten/unflatten in case of nullability

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/avro-schema#63]
This kind of fields does not work at all. For more details see #62 .

### How it had to have been implemented (1 proposal, Kiril)
- There is a marker which is placed before each nullable type which is  :
  1. `0` if next field is null
  2. `1` if next field is not null   
- All fields of nullable record type are encoded in a subarray and therefore consume 2 places in the array (1 for an indicator, 1 for an array)

Adv:
1. It may work

Dis:
1. It consumes extra space for each nullable element
2. We should update 2 fields (indicator and a value) for nullable types
3. We cannot update field inside of a nullable record (xflatten), because it is stored in a subarray
    - json path is not implemented yet in Tarantool
    - !!!! we cannot update a field without checking nullability of each of its parents, which requires `select`; see more info below
4. It is hard to be implemented over current AVRO

### No array, no indicator, allow nullable records (2 proposal, nazarov)

- Encode only fields of nullable record type with indicator, scalar types are encoded without an indicator.
- Do not use an array for a field of nullable record type, instead, in case of nullable  record field, emit null indicator and nulls instead of each of its fields
Adv:
1. Do not  consume space for indicators
2. We can index fields inside of a nullable records
3. We can easily update  nullable scalars inside of non nullable records
4. Do not require migration from nonnullable to nullable for scalars

Dis:
1. We have to set null to each field inside of nullable record if we make the record to be a null
2. !!!!!!! we cannot update a field without checking nullability of each of its parents, which requires `select`; see more info below
3. It is hard to be implemented over current AVRO

### No array, No indicator, No nullable records (3 proposal, alex)

- only scalars, maps and arrays and fixed are allowed to be nullable
- any type of a nyllable is encoded without an indicator

Adv:
1. Do not  consume space for indicators
2. Can create an index over any field
3. Can easily update any field with a tarantool update statement
4. Relatively easy to implement
5. Do not require migration from non nullable to nullable
6. It is the first phase of implementing solution [4], more advanced

Dis:
1. fields of nullable record type are prohibited

### Array, No indicator, nullable records (4 proposal, alex)

- Any type is encoded without an indicator
- Arrays are used to represent any nullable records (or any record)

Adv:
1. Do not  consume space for indicators
2. Can create an index over any field
3. Can easily update any field with a tarantool update statement
4. Do not require migration from nonnullable to nullable for scalars

Dis:
1. it requires json path feature in tarantool first
2. It is medium hard to be implemented over current AVRO

### Why select is very bad:
In some of the solutions the select is required, which means that we have to request a record first and than decide, how it should be updated.
Problems with this approach:
1. It does not work atomically over a cluster.
2. It is slower.

## Discussions
1. @racktear  said that he do not use flatten at all
2. @Kasen  said that he want to prohibit nullable records in bastida even if we do not do it in avro
3. @Kasen  said that he likes 3 approach because it do not require a migration

## Decision
In my oppinion the solution is obvious:
1. Implement 3 option first
2. extend 3 to 4 (They are backward compatible)

**Comment by Totktonada** [comment]
Nullable for records is the main part of the nullability feature. The intention is to represent a field of object type that can be null to avoid schema decompisition over several spaces and full-object-construction operation on an application side.

We cannot flatten nullable record, because the first field can be nullable too: these case become non-distinguishable.

After json path support will be added to tarantool, update of nested field of NULL object should give an error on tarantool side, IMO.

**Comment by Khatskevich** [comment]
There was a meeting with me, @Totktonada and @kyukhin.
It was decided that current strategy is to implement `4` approach.
The first aim is to make nullable scalars working.
