### ISSUE TITLE
Debian package build for ubuntu:bionic fails

### ISSUE THREAD

**Issue by SudoBobo** [tarantool/avro-schema#96]
https://travis-ci.org/tarantool/avro-schema/jobs/391685446

**Comment by Totktonada** [comment]
I guess it is because we have no packages for bionic in 1_7 packagecloud repository. Now I set the repository to 1_9 and will try to update targets soon.

**Comment by Totktonada** [comment]
I need to update it again to 1_10, because tarantool-1.9 is not built for recent distros such as Fedora >= 28. Now everything looks good: https://github.com/tarantool/avro-schema/pull/122
